
name: Publish and Deploy Package

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Draft Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract package.json Info
      id: projectinfo
      uses: gregoranders/nodejs-project-info@v0.0.5
    - name: Draft Release
      uses: release-drafter/release-drafter@v5.9.0
      with:
        version: ${{ steps.projectinfo.outputs.version }}
        prerelease: ${{ startsWith(steps.projectinfo.outputs.version, '0.') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: '12'
      - name: Install dependencies
        run: npm ci
      - name: Publish package to Github
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm ci
      - name: Cat for GitHub Actions
        uses: pCYSl5EDgo/cat@1.0.0
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "research-server" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: "heroku/nodejs" #OPTIONAL
